### ISSUE TITLE
About gen_params

### ISSUE THREAD

**Issue by Xiaofu233** [wangguanan/JSIA-ReID#1]
gen_params = list(set(gen_params).difference(set(sl_enc_params).union(set(il_enc_params))))

why gen_params include  il_enc_params?

Thank you!

**Comment by wangguanan** [comment]
gen_params include no il_enc_params.
```
gen_params = list(set(gen_params).difference(set(sl_enc_params).union(set(il_enc_params))))
```
means
```
gen_params - (sl_enc_params+il_enc_params)
```
