### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by stormyoung** [wangguanan/JSIA-ReID#2]
![image](https://user-images.githubusercontent.com/13610136/83591115-bf7d8b80-a589-11ea-940c-0f7dc68629e0.png)
王博士您好，在您train.py代码中，第87行，为什么使用base.generator_rgb，而不使用 base.generator_ir?

**Comment by stormyoung** [comment]
最后生成的图片应该是IR图片，所以不是应该使用base.generator_ir么？是我哪里理解的不对么，希望得到您的指导~

**Comment by wangguanan** [comment]
感谢你的意见。我们已经改正了这个错误。
