### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by 17634232772** [wangguanan/JSIA-ReID#4]
作者你好，我下载了你的预训练模型，想测试，但出现了这个错误Runerror:unexpected EDF,expected1740278 more bytes.the file might be corrup，请问是什么原因？

**Comment by hankhaohao** [comment]
@17634232772   I encountered the same problem, have you solved it now？

**Comment by wangguanan** [comment]
我去看看。

**Comment by 17634232772** [comment]
请问预训练模型有问题么？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangguanan/JSIA-ReID"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月22日(星期三) 下午3:57
收件人:&nbsp;"wangguanan/JSIA-ReID"<JSIA-ReID@noreply.github.com&gt;;
抄送:&nbsp;"可乐"<1209215536@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wangguanan/JSIA-ReID] test error (#4)





 
我去看看。

**Comment by wangguanan** [comment]
你好，确实是模型的问题。应该是我下载模型的时候没有下载全。
我再重新训练一遍，传上去。
你们也可以直接运行train，自己train一个。

**Comment by 17634232772** [comment]
好的，谢谢您！
------&nbsp;原始邮件&nbsp;------
发件人:&quot;wangguanan&quot;<notifications@github.com&gt;;
发送时间:2020年7月31日(星期五)&nbsp;晚上10:38
收件人:&quot;wangguanan/JSIA-ReID&quot;<JSIA-ReID@noreply.github.com&gt;;
抄送人:&quot;17634232772&quot;<1209215536@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:Re:&nbsp;[wangguanan/JSIA-ReID]&nbsp;test&nbsp;error&nbsp;(#4)



 
你好，确实是模型的问题。应该是我下载模型的时候没有下载全。
 我再重新训练一遍，传上去。
 你们也可以直接运行train，自己train一个。
 
&mdash;

**Comment by 17634232772** [comment]
您好，我尝试复现您在githup上发布的关于JSIA-ReID的开源代码，但是测试出来的结果和您论文中的相差很大，但不知道为什么会这样，所以想咨询一下您，是不是有些技巧没有体现在开源代码中？还是什么别的原因。
而且，还想请问一下，最后测试显示的结果是mAp还是R1？请看到后不吝赐教，谢谢您！













------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangguanan/JSIA-ReID"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 晚上10:38
收件人:&nbsp;"wangguanan/JSIA-ReID"<JSIA-ReID@noreply.github.com&gt;;
抄送:&nbsp;"可乐"<1209215536@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wangguanan/JSIA-ReID] test error (#4)





 
你好，确实是模型的问题。应该是我下载模型的时候没有下载全。
 我再重新训练一遍，传上去。
 你们也可以直接运行train，自己train一个。

**Comment by lzw-wo** [comment]
您好，我在测试的时候也遇到了模型错误的问题（RuntimeError: unexpected EOF, expected 1740278 more bytes. The file might be corrupted.） 不知您方不方便重新发一下pretrained_model，非常感谢！

**Comment by wangguanan** [comment]
你好，抱歉拖了这么久。
之前的模型因为网络原因，没有上传成功，所以报错。（100MB的文件只上传了一半）
我重新训练了一波模型，然后上传到 google drive 和 baidu disk。
你们现在可以重新下载（所有4个文件）。然后测试模型了。谢谢。

**Comment by lzw-wo** [comment]
非常感谢您！

**Comment by 17634232772** [comment]
非常感谢您的回信，感谢感谢！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangguanan/JSIA-ReID"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月6日(星期二) 晚上7:17
收件人:&nbsp;"wangguanan/JSIA-ReID"<JSIA-ReID@noreply.github.com&gt;;
抄送:&nbsp;"可乐"<1209215536@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [wangguanan/JSIA-ReID] test error (#4)





 
你好，抱歉拖了这么久。
 之前的模型因为网络原因，没有上传成功，所以报错。
 我重新训练了一波模型，然后上传到 google drive 和 baidu disk。
 你们现在可以重新下载（所有4个文件）。然后测试模型了。谢谢。
